# Generated by Django 3.1.3 on 2021-05-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('avatar', models.CharField(max_length=255)),
                ('nome_slack', models.CharField(max_length=255)),
            ],
        ),
    ]
