# Generated by Django 3.1.3 on 2021-05-20 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sorteador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Sorteio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('notificado', models.BooleanField(default=False)),
                ('facilitador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilitador', to='sorteador.participante')),
                ('secretario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretario', to='sorteador.participante')),
            ],
        ),
    ]
